name: Download and Save File

on: [push]

permissions:
  contents: read

jobs:
  download-file:
    runs-on: windows-latest

    steps:
      - name: Create download directory
        run: |
          if (-Not (Test-Path -Path "D:\testload")) {
            New-Item -ItemType Directory -Path "D:\testload"
          }

      - name: Download file from GitHub release
        shell: pwsh
        run: |
          $url = "https://github.com/<owner>/<repo>/releases/download/<tag>/Python_2DB.exe"
          $output = "D:\testload\Python_2DB.exe"
          Invoke-WebRequest -Uri $url -OutFile $output

      - name: Upload exe to artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python_2DB
          path: "**/Python_2DB.exe" 
